version: '3'
services:

  db:
    image: mariadb:10.7.3
    container_name: db
    volumes:
      - ./wp-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:5.9.3-php7.4-fpm-alpine
    volumes:
      - ./config/php/php.conf:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USERNAME}
      WORDPRESS_DB_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    restart: always
    links:
      - db
    depends_on:
      - db
    networks:
      - wordpress-network

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./wp-app:/var/www/html
      - ./log/nginx:/var/log/nginx
    ports:
      - 8080:80
    links:
      - wordpress
    networks:
      - wordpress-network

  pma:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    links:
      - db:db
    networks:
      - wordpress-network

volumes:
    wordpress:
    db:

networks:
  wordpress-network:
      driver: bridge
