FROM wordpress:6.0.2-php8.0-fpm-alpine

RUN apk update && apk add \
    mc \
    git \
    vim \
    tcpdump \
    nginx \
    supervisor \
    gcc \
    g++ \
    make \
    autoconf \
    gnu-libiconv

RUN pecl install xdebug && docker-php-ext-enable xdebug
